### ISSUE TITLE
https://ydtdml.com

### ISSUE THREAD

**Issue by 1832070282** [abbw/blog_links#5]
## 站点名称[必填]
name: 钰嵩君

## 站点链接[必填]
link: https://ydtdml.com

## 站点头像[必填]
avatar: https://ydtdml.com/logo.jpg

## 站点描述[必填]
descr: 简短而深情，总有一句为你而写

## 如有截图自行添加图片URL，`:` 后务必添加一个空格
Screenshot:  https://s1.ax1x.com/2020/10/09/0Dy27T.png

**Comment by abbw** [comment]
站点友链不存在，已 Close
